# Generated by Django 5.1.7 on 2025-03-27 12:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('current_question', models.IntegerField(default=1)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_quizzes', to='app.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_skipped', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.answeroption')),
                ('user_quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='app.userquiz')),
            ],
            options={
                'ordering': ['question__order'],
                'unique_together': {('user_quiz', 'question')},
            },
        ),
    ]
