# Generated by Django 5.1.7 on 2025-03-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userquiz_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquiz',
            name='reflection_1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='reflection_2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquiz',
            name='reflection_3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
